version: '3'

services:
  web:
    build: .
    container_name: django_app
    command: gunicorn pillproof.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    expose:
      - 8000

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - .:/app                   # gives Nginx access to /app/static/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
